### PR TITLE
Render a placeholder element, get the container size, and only then render

### LINKED ISSUE #1: Initial values
Thank you for this very handy project! I have just made a PR to add it to Recharts (http://recharts.org), but there is a minor thing that makes them sort of incompatible.

React-container-dimensions is always sending its initial state (width and height set to zero) to the children components on the first render, and therefore Recharts prints multiple warns saying that it can't render the charts in these conditions.

Can we send others values, other than zeros, to the children? What about having a third parameter `hasInitiated`, or send `null` as first values?

Link to the PR: recharts/recharts#105

### PR DESCRIPTION
**Pull request by zvictor**
fix #1

### CODE REVIEW

**Comment by okonet** [comment]
Awesome! I like this approach! Can you please also add test cases and I'd be happy to merge it.

**Comment by zvictor** [comment]
all the features are already being tested and passing.

I don't think we should test if we initially rendered a placeholder or not, the same way it was not testing before if a `children` was being initially rendered with `{ width: 0, height: 0}`

**Comment by okonet** [comment]
> I don't think we should test if we initially rendered a placeholder or not

Why not? I think this is now quite important to test

> it was not testing before if a children was being initially rendered with { width: 0, height: 0}

You're right. I missed this one. I've just added such a test in https://github.com/okonet/react-container-dimensions/commit/d84fedf0a3b979a43d80caa141eb8d7b9839a834

**Comment by zvictor** [comment]
how can I check the content of the initial render, before `componentDidMount`?

**Comment by zvictor** [comment]
there you go.
It conflicts with the tests you just created. I haven't fixed because you have to decide if you want to keep the tests you just created or not.

**Comment by okonet** [comment]
Thanks! I'll merge and take a look at tests myself. Either way I think it's a great improvement over the current state!

**Comment by zvictor** [comment]
please let us know at recharts/recharts#105 when you merge it

**Comment by zvictor** [comment]
Shouldn't we publish a new version on npm?

**Comment by okonet** [comment]
Will do now. Thanks!

**Pull request merged**
