### PR TITLE
[Typescript] Create Typescript definitions

### PR DESCRIPTION
**Pull request by franklixuefei**

### CODE REVIEW

**Review by okonet — APPROVED** [review]

**Comment by franklixuefei** [comment]
@okonet I saw you approved the other one already. Thanks! 😄 This one was just a dupe.

**Comment by franklixuefei** [comment]
Would you consider a release for this? :-D

**Comment by okonet** [comment]
This was released automatically right after the merge.

**Comment by okonet** [comment]
Oh sorry. The release failed with 0 code 🤷‍♂️ Because of npm security.

**Comment by okonet** [comment]
I’ll try to trigger ASAP

**Comment by okonet** [comment]
It's now released as 1.4.0. Thanks!

**Pull request merged**
